--- #APTREPO Module
- hosts: Debian
  remote_user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing dependencies needed for apt_repo
    apt: pkg=python-apt state=latest
  - name: Adding a repo key
    apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  - name: Adding report to /etc/apt/sources.list
    apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" state=present
