--- #HTPASSWD module
- hosts: all
  remote_user: test
  gather_facts: yes
  become: yes
  connection: ssh
  tasks:
  - name: Installing python-passlib on Debian
    apt: pkg=python-passlib state=installed
    when: ansible_os_family == 'Debian'
  - name: Creating a user using htpasswd module
    htpasswd: path=/etc/apache2/.htpasswd name=test2 mode=0777 owner=root group=root password=test2
    when: ansible_os_family == 'Debian'
