--- #Kernel Module
- hosts: all
  remote_user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Adding a dummy module to black list
    kernel_blacklist: name=dummy state=present
