--- #USER Module
- hosts: all
  connection: ssh
  gather_facts: no
  remote_user: test
  become: yes
  tasks:
  - name: removing users
    user: name={{ item }} state=absent
    with_items:
    - user1
    - user2
